Joint_mass_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: Joint_mass
    joint_speed: 1.47
    motor:
        id: 4
        init: 512
        min: 0
        max: 1023


